[package]
name = "yousearch-api"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "yousearch_lib"
path = "src/lib.rs"

[[bin]]
name = "yousearch_bin"
path = "src/main.rs"

[dependencies]
shuttle-service = { version = "0.11.0", features = ["web-rocket"] }
rocket = "0.5.0-rc.2"
tokio = "1.21.0"
futures = "0.3"